#!/bin/bash
echo -e "  \033[100m    DIARIO DEL DESARROLADOR       "
echo "ACTUALMENTE ESTOY ARREGLANDO ERRORES"
echo "TAMBIEN AUMENTANDO LA COMPATIBILIDAD"
echo "EN ESTOS DIAS ESTARE AGREGANDO ALGO NUEVO, MANTENTE ATENT@"
echo "GRACIAS POR PASARTE, VUELVE PRONTO"
msg -ne "Enter Para Continuar" && read enter

